# This file describe Keywords that are required to seek into the log, and what to do once the log was extracted

[systemmd]

[CRON]

[anacron]

[cron-apt]

[postfix]

[omv]

[kernel]

[php]

[smbd]

[monit]

[avahi]

[clamd]

[freshclam]

[rsyslogd]

[openmediavault]

[mkworkbench]

[sfsnapadm]
